=== Espi13/MLIMS/lmsgi-xml/lmsgi-xml/alumnos_notas.dtd
<!ELEMENT clase (alumno+)>
<!ELEMENT alumno (nombre,apellido,DNI,tel,email,calificaciones)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT DNI (#PCDATA)>
<!ELEMENT tel (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT calificaciones (asignatura+)>
<!ELEMENT asignatura (nombre,nota*)>
<!ELEMENT nota (tipo,cal)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT cal (#PCDATA)>


<!--<!ATTLIST alumno nexp CDATA #REQUIRED>-->
<!--<!ATTLIST alumno nexp CDATA #FIXED "0000">--> 
<!-- Si existe tiene que tener ese valor-->
<!ATTLIST email visible (si|no|grupo) "si"> <!--Valor por defecto "si"-->

<!--Clase atributo id, obligatorio
     Alumno atributo nacionalidad, por defecto espaÃ±ola
     Asignatura atributo horas enumerado 3 4 6 8
     Nota atributo puntos opcional
     -->
     
<!ATTLIST clase id CDATA #REQUIRED>
<!--
<!ATTLIST clase id NMTOKEN #REQUIRED>
 NMTOKEN= no puede contener espacio-->
<!ATTLIST alumno nacionalidad CDATA "espaÃ±ola">
<!ATTLIST asignatura horas (3|4|6|8) #IMPLIED>
<!ATTLIST nota punto CDATA #IMPLIED>
<!--Restriccion de nmtoken y no se puede repetir-->
<!ATTLIST alumno nexp ID #REQUIRED>
<!--Debe de existir algun valor-->
<!ATTLIST nota nexp_ref IDREF #IMPLIED>

=== Espi13/MLIMS/lmsgi-xml/lmsgi-xml/alumnos_notas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE clase SYSTEM "alumnos_notas.dtd">
<clase id="daw1">
<alumno nexp="A1234" nacionalidad="francesa" >
<nombre>Jose</nombre>
<apellido> de la pradera</apellido>
<DNI>56748952F</DNI>
<tel>654213789</tel>
<email visible="no">josepradera@pruebas.com</email>
<calificaciones>
  <asignatura>
    <nombre>LMSGI</nombre>
    <nota nexp_ref="A1234">
    <tipo>1ev</tipo>
    <cal>7</cal>
    </nota>
  </asignatura>
</calificaciones>
</alumno>
<alumno nexp="A12345">
<nombre>Paco</nombre>
<apellido>Villuela</apellido>
<DNI>567445642F</DNI>
<tel>65424489</tel>
<email visible="grupo">pacogarcia@pruebas.com</email>
<calificaciones>
  <asignatura >
    <nombre>LMSGI</nombre>
    <nota punto="7">
    <tipo>1ev</tipo>
    <cal>7</cal>
    </nota>
  </asignatura>
</calificaciones>
</alumno>

</clase>
